# Generated by Django 4.2.7 on 2023-12-21 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha_inscripcion', models.DateField()),
                ('hora_inscripcion', models.TimeField()),
                ('estado', models.CharField(choices=[('Reservado', 'Reservado'), ('Completa', 'Completa'), ('Anulada', 'Anulada'), ('No Asisten', 'No Asisten')], max_length=20)),
                ('observacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seminario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha_in', models.DateField()),
                ('institucion', models.CharField(max_length=50)),
                ('hora_in', models.TimeField()),
                ('estado', models.CharField(choices=[('Reservado', 'Reservado'), ('Completa', 'Completa'), ('Anulada', 'Anulada'), ('No Asisten', 'No Asisten')], max_length=20)),
                ('observacion', models.CharField(max_length=200)),
                ('inscritos', models.ManyToManyField(to='prueba_3_app.inscrito')),
            ],
        ),
        migrations.AddField(
            model_name='inscrito',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba_3_app.institucion'),
        ),
    ]
