# Generated by Django 4.2.7 on 2023-12-22 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_3_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='observacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='seminario',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seminario',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba_3_app.institucion'),
        ),
        migrations.AlterField(
            model_name='seminario',
            name='observacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
